// HUMECCA 고객사 데이터
// 이 파일을 수정하여 고객사를 관리하세요

const CUSTOMER_DATA = [
    { name: 'METACITY', logo: '' },
    { name: 'e-대구은행', logo: '' },
    { name: 'JNESS', logo: '' },
    { name: '피넷', logo: '' },
    { name: '원데이', logo: '' },
    { name: 'NDS (녹십자데이터시스템)', logo: '' },
    { name: '한국전교역사기념관', logo: '' },
    { name: '서울창업창업재단', logo: '' },
    { name: 'PFIN', logo: '' },
    { name: '메타디씨', logo: '' },
    { name: '디담365', logo: '' },
    { name: '블랭에이아이', logo: '' },
    { name: '버튼스카드', logo: '' },
    { name: '네오스포트', logo: '' },
    { name: '제이니스', logo: '' },
    { name: '알파스포트', logo: '' },
    { name: '아이티더블유유피엠엘프코리아', logo: '' },
    { name: '푸퍼스트', logo: '' },
    { name: '지엔뎬바로보스', logo: '' },
    { name: '세계무용엠앰', logo: '' },
    { name: '아이에이엠', logo: '' },
    { name: '즐거움푸드', logo: '' },
    { name: '엑시즌씨엠앤스', logo: '' },
    { name: '메디스쿱가스', logo: '' },
    { name: '아트앤달려버니', logo: '' },
    { name: '민플릿', logo: '' },
    { name: '마인스포트', logo: '' },
    { name: '비아이엠솔루션선', logo: '' },
    { name: '당페이나에이엔시', logo: '' },
    { name: '스카이엠켑', logo: '' },
    { name: '아이디엠스', logo: '' },
    { name: '에이티브애일', logo: '' },
    { name: '브랜드스탭', logo: '' },
    { name: '쓰리앰시스', logo: '' },
    { name: '그림닷컴', logo: '' },
    { name: '아이비스코퍼레이션', logo: '' },
    { name: '아롬아이디자인', logo: '' },
    { name: '포스제이스', logo: '' },
    { name: '마이드스탭', logo: '' },
    { name: '가이드코인', logo: '' },
    { name: '메타비티', logo: '' },
    { name: 'KT', logo: '' },
    { name: '삼성전자', logo: '' },
    { name: 'LG전자', logo: '' },
    { name: '현대자동차', logo: '' },
    { name: 'SK텔레콤', logo: '' },
    { name: '네이버', logo: '' }
];
